name: Build & Deploy Pages (no commits)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # hourly UTC; guarded to 5am ET + every 3h

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Schedule guard (5am ET + every 3h)
        if: ${{ github.event_name == 'schedule' }}
        run: |
          HOUR=$(TZ=America/New_York date +%H)
          if [ "$HOUR" -eq 5 ] || [ $(( (10#$HOUR - 5) % 3 )) -eq 0 ]; then
            echo "Proceeding at $HOUR:00 ET"
          else
            echo "Skipping at $HOUR:00 ET (not in schedule)"; exit 78
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
                  cache: "pip"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install -r requirements.txt

      - name: Generate site data (JSON/CSV/RSS)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/gather.py
          test -f docs/daily.json || (echo "daily.json missing" && exit 1)

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
